### ISSUE TITLE
Impossible to connect & create a form, just after the installation

### ISSUE THREAD

**Issue by Nartagnan** [YunoHost-Apps/framaforms_ynh#35]
**Describe the bug**
I installed Framaforms, but each time I try to connect, I'm sent back to my YunoHost user interface (XXX.ynh.fr/yunohost/sso/)

**Versions**
- Hardware: Recycled laptop,
  - Lenovo Thinkpad x240
  - CPU : Intel i7-4600U @ 2.1GHz

- YunoHost version: 4.0.8.2 (stable)

- I have access to my server : through SSH & through the webadmin & direct access via keyboard / screen

- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? No

**To Reproduce**
Install Framaforms
- FR / No expiration date / No suppression / **visitors cannot join nor create a form**

Go to XXX.ynh.fr/poll/ while being loged in YunoHost SSO

Click on "m'identifier" or "se connecter"

Be rederected on the same page or the XXX.ynh.fr/yunohost/sso/

**Expected behavior**
I expect to access the "create a form" page

**Comment by Nartagnan** [comment]
I uninstalled it and re-installed it with
**visitors can join or create a form**

but same behavior, "Create a form" or "create an account" send back to SSO

**Comment by Bertrand134** [comment]
Same issue for me. Did you find a solution ?

**Comment by Nartagnan** [comment]
Sorry, I didn't try again

**Comment by isAAAc** [comment]
this bug is still alive on a fresh install :-1: 
```
# yunohost -v
yunohost: 
  repo: stable
  version: 4.3.6.3
yunohost-admin: 
  repo: testing
  version: 4.3.4.1
moulinette: 
  repo: stable
  version: 4.3.3.1
ssowat: 
  repo: stable
  version: 4.3.3.1
```
