### ISSUE TITLE
Can't access to admin interface

### ISSUE THREAD

**Issue by mrtpcet** [YunoHost-Apps/framaforms_ynh#36]
I can't access to admin interface on my subdomain `formulaires.mydomain.fr/admin`

It's show me 
`Accès refusé`
```
La page que vous demandez n'est pas accessible parce que vous ne semblez pas avoir les droits suffisants pour y accéder.
Commencez d'abord par vous identifier, ou vous créer un compte, puis rééssayez.
You can't reach this page because you don't seem to have appropriate rights to access it.
Please register or login first, then try again
```

**So i can't activate new accounts**

**Comment by mrtpcet** [comment]
I have to add myself `Framaforms (Admin)` in `WebAdmin > User > Manage Group and permissions`

**Comment by isAAAc** [comment]
```
# yunohost -v
yunohost: 
  repo: stable
  version: 4.3.6.3
yunohost-admin: 
  repo: testing
  version: 4.3.4.1
moulinette: 
  repo: stable
  version: 4.3.3.1
ssowat: 
  repo: stable
  version: 4.3.3.1
```
it works for me, 
@mrtpcet do you confirm it is fixed on your side too ? (if yes we could close this issue)
