### ISSUE TITLE
admin page tells drupal needs an update

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/framaforms_ynh#57]
hello, 
```
# yunohost -v
yunohost: 
  repo: stable
  version: 4.3.6.3
yunohost-admin: 
  repo: testing
  version: 4.3.4.1
moulinette: 
  repo: stable
  version: 4.3.3.1
ssowat: 
  repo: stable
  version: 4.3.3.1
```
when on the admin page, a warning message pop up on the top telling drupal need a security upgrade
```
Une mise à jour de sécurité est disponible pour votre version de Drupal. Afin de garantir la sécurité de votre serveur, effectuez immédiatement la mise à jour ! Consultez la page des [mises à jour disponibles](https://mcpletsch.org/poll/admin/reports/updates/update) pour plus d'informations et pour installer les mises à jour manquantes.
    Des mises à jour de sécurité sont disponibles pour un ou plusieurs de vos modules ou thèmes. Afin de garantir la sécurité de votre serveur, effectuez immédiatement la mise à jour ! Consultez la page des [mises à jour disponibles](https://mcpletsch.org/poll/admin/reports/updates/update) pour plus d'informations et pour installer les mises à jour manquantes.
```
